name: FruitWars
version: 0.0.1
author: Hakan Staby
description: 'The master cake race has come to enslave the peaceful Fruits. You must
  push the attackers back to where they came from. You do it with the only tool you
  know: fruit!'
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  play_phaser: any
