name: CakeWars
version: 1.0.0
author: Hakan Staby <hakan.staby@gmail.com>
description: "Stop the Cake master race before they assert their world domination\
  \ by global teeth decay! \r\nYou do it with the only tool you know: Fruit!"
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  play_phaser: '>=0.12.2 <0.13.0'
